version: "3.8"
services:
  gitbook:
    image: fellah/gitbook
    container_name: gitbook
    entrypoint: /bin/bash
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"  # 开发使用的测试端口
    volumes:
      - ./:/srv/gitbook/musicatri  # github pages应用根目录
      - ./copyPluginAssets.js:/root/.gitbook/versions/3.2.0/lib/output/website/copyPluginAssets.js  # gitbook打包问题修复
