# 开发环境compose文件，仅包含开发环境镜像容器
version: "3.8"
name: musicatri
services:
  neteasecloudmusicapi:  # 网易云音乐api
    hostname: neteasecloudmusicapi
    image: binaryify/netease_cloud_music_api:${NETEASECLOUDMUSICAPI_TAG}
    ports:
      - "3000:3000"  # 测试环境下使用此端口连接neteasecloudmusicapi音乐api服务
    restart: unless-stopped

  mongodb:  # 音乐机器人数据库
    hostname: mongodb
    image: mongodb/mongodb-community-server:${MONGODB_TAG}
    ports:
      - "27017:27017"  # 测试环境下使用此端口连接mongodb数据库服务
    restart: unless-stopped
#    开发环境下Mongodb不需要挂载数据卷
#    volumes:
#       mongodb日志文件: /data/db/.mongodb/mongosh/*.log
#      - mongodb-data:/data/db
#      - ./mongodb.conf:/etc/mongodb.conf

  clash:  # clash代理
    image: laoyutang/clash-and-dashboard:${CLASH_TAG}
    hostname: clash
    restart: unless-stopped
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml  # clash配置文件
    ports:
      - "7888:8080"  # 请不要在生产环境暴露clash控制面板端口
      - "7890:7890"  # 测试环境下使用例如proxychains连接此clash代理

volumes:
  mongodb-data:  # mongodb数据库存储数据持久化

